# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "nozomi"
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josh Price"]
  s.date = "2012-02-29"
  s.description = "Opinionated Rails project templating"
  s.summary = "Get your rails projects going faster with Nozomi"
  s.email = "josh@canoniq.com"
  s.executables = ["nozomi"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown",
    "TODO"
  ]
  s.files = [
    "Gemfile",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "TODO",
    "VERSION",
    "bin/nozomi",
    "lib/nozomi.rb",
    "lib/nozomi/cli.rb",
    "lib/nozomi/interactive.rb",
    "lib/nozomi/template.rb",
    "lib/rails3-template.rb",
    "lib/templates/bootstrap-sass.rb",
    "lib/templates/core.rb",
    "lib/templates/cucumber.rb",
    "lib/templates/decent_exposure.rb",
    "lib/templates/devise.rb",
    "lib/templates/factory_girl.rb",
    "lib/templates/fakeweb.rb",
    "lib/templates/formtastic.rb",
    "lib/templates/git.rb",
    "lib/templates/guard.rb",
    "lib/templates/haml.rb",
    "lib/templates/jquery.rb",
    "lib/templates/machinist.rb",
    "lib/templates/rspec.rb",
    "lib/templates/standard.rb",
    "nozomi.gemspec"
  ]
  s.homepage = "http://github.com/joshprice/nozomi"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 0"])
      s.add_runtime_dependency(%q<clamp>, [">= 0"])
      s.add_development_dependency(%q<rake>, ["= 0.8.7"])
      s.add_development_dependency(%q<jeweler>, ["= 1.5.1"])
    else
      s.add_dependency(%q<rails>, [">= 0"])
      s.add_dependency(%q<clamp>, [">= 0"])
      s.add_dependency(%q<rake>, ["= 0.8.7"])
      s.add_dependency(%q<jeweler>, ["= 1.5.1"])
    end
  else
    s.add_dependency(%q<rails>, [">= 0"])
    s.add_dependency(%q<clamp>, [">= 0"])
    s.add_dependency(%q<rake>, ["= 0.8.7"])
    s.add_dependency(%q<jeweler>, ["= 1.5.1"])
  end
end

