apply template('bootstrap-sass')
apply template('formtastic')
apply template('haml-and-sass')
apply template('devise')
apply template('rspec')
apply template('factory-girl')
apply template('guard')
apply template('jquery')
